### ISSUE TITLE
multi-microgrids environment

### ISSUE THREAD

**Issue by WDzhd** [ahalev/python-microgrid#101]
Hi,
I am currently conducting research on optimization of multi-microgrid system witn shared energy storage based on multi-agent deep reinforcement learning. The model involves multiple microgrids and shared energy storage stations. Can your project achieve the generation of the above model? If I need to modify your code, could you give me some suggestions?

**Comment by ahalev** [comment]
That would appear to be a viable use case. You would need to initialize multiple `Microgrid` objects with the same `Battery` object. You may need to subclass `Microgrid._get_module_container` to remove the `deepcopy` call to ensure the battery references point to the same object.
