### ISSUE TITLE
Availability by time series (EV) battery

### ISSUE THREAD

**Issue by TEKaal** [ahalev/python-microgrid#105]
## Issue Type

Select one:

**[] Bug report**
**[] Question**
**[x] Feature Request**
**[] Other**

Fill these out:

* **python-microgrid version**:
---

## Feature Request

EV batteries that are (un)available.

* #### Problem this feature solves:

It makes it possible to take in Electric Vehicles in the system. 

* #### Desired solution:
I was wondering whether it might be possible to add the possibility to add a time series with availability for batteries. This in order to mimic Electric Vehicles. 

Example: I want some EV batteries taken in and they would leave the microgrid at 7 am and return at 18 pm with a random SOC.

**Comment by ahalev** [comment]
Interesting idea. If you were interested in proposing an implementation, I would happily take a look at a PR. I imagine you could subclass `BatteryModule` and add in some time-dependent functionality.
