### ISSUE TITLE
Error loading continuous OpenAI-Gym environment from pymgrid25

### ISSUE THREAD

**Issue by BZ03SL** [ahalev/python-microgrid#56]
Hi, I encountered an issue when I tried to load a continuous environment from pymgrid25 (details specified below) following the simple example from the documentations. Is this because the given pymgrid benchmarks only support discrete environments or is there anything I was doing wrong?
Thanks in advance!

### Code for error reproduction on Colab:
```
!pip install -U python-microgrid
import numpy as np
import pandas as pd
np.random.seed(0)
from pymgrid import Microgrid
from pymgrid.modules import (
    BatteryModule,
    LoadModule,
    RenewableModule,
    GridModule)
from pymgrid.envs import ContinuousMicrogridEnv
env = ContinuousMicrogridEnv.from_scenario(microgrid_number=0)
```

### Full error stack:
ValueError                                Traceback (most recent call last)
[<ipython-input-6-2da5e07cf75b>](https://localhost:8080/#) in <cell line: 2>()
      1 from pymgrid.envs import ContinuousMicrogridEnv
----> 2 env = ContinuousMicrogridEnv.from_scenario(microgrid_number=0)

9 frames
[/usr/local/lib/python3.10/dist-packages/pymgrid/envs/base/base.py](https://localhost:8080/#) in from_scenario(cls, microgrid_number, **kwargs)
    295     @classmethod
    296     def from_scenario(cls, microgrid_number=0, **kwargs):
--> 297         env = super().from_scenario(microgrid_number=microgrid_number)
    298 
    299         if kwargs:

[/usr/local/lib/python3.10/dist-packages/pymgrid/microgrid/microgrid.py](https://localhost:8080/#) in from_scenario(cls, microgrid_number)
   1000 
   1001         with open(PROJECT_PATH / f"data/scenario/pymgrid25/microgrid_{n}/microgrid_{n}.yaml", "r") as f:
-> 1002             return cls.load(f)
   1003 
   1004     def _dir_additions(self):

[/usr/local/lib/python3.10/dist-packages/pymgrid/envs/base/base.py](https://localhost:8080/#) in load(cls, stream)
    304     @classmethod
    305     def load(cls, stream):
--> 306         return cls(super().load(stream))

[/usr/local/lib/python3.10/dist-packages/pymgrid/envs/base/base.py](https://localhost:8080/#) in __new__(cls, modules, *args, **kwargs)
     69                           'Use from_microgrid() instead.', category=FutureWarning)
     70 
---> 71             instance = cls.from_microgrid(modules, **kwargs)
     72 
     73         elif isinstance(modules, int):

[/usr/local/lib/python3.10/dist-packages/pymgrid/envs/base/base.py](https://localhost:8080/#) in from_microgrid(cls, microgrid, **kwargs)
    286         kwargs['trajectory_func'] = kwargs.pop('trajectory_func', microgrid.trajectory_func)
    287 
--> 288         return cls(modules.to_tuples(), **kwargs)
    289 
    290     @classmethod

[/usr/local/lib/python3.10/dist-packages/pymgrid/envs/base/base.py](https://localhost:8080/#) in __init__(self, modules, add_unbalanced_module, loss_load_cost, overgeneration_cost, reward_shaping_func, trajectory_func, flat_spaces, observation_keys)
    104         self.observation_keys = self._validate_observation_keys(observation_keys)
    105 
--> 106         self.action_space = self._get_action_space()
    107         self.observation_space, self._nested_observation_space = self._get_observation_space()
    108 

[/usr/local/lib/python3.10/dist-packages/pymgrid/envs/continuous/continuous.py](https://localhost:8080/#) in _get_action_space(self)
     60     def _get_action_space(self):
     61         self._nested_action_space = self._get_nested_action_space()
---> 62         return flatten_space(self._nested_action_space) if self._flat_spaces else self._nested_action_space
     63 
     64     def _get_action(self, action):

[/usr/lib/python3.10/functools.py](https://localhost:8080/#) in wrapper(*args, **kw)
    887                             '1 positional argument')
    888 
--> 889         return dispatch(args[0].__class__)(*args, **kw)
    890 
    891     funcname = getattr(func, '__name__', 'singledispatch function')

[/usr/local/lib/python3.10/dist-packages/gym/spaces/utils.py](https://localhost:8080/#) in _flatten_space_dict(space)
    381         space_list = [flatten_space(s) for s in space.spaces.values()]
    382         return Box(
--> 383             low=np.concatenate([s.low for s in space_list]),
    384             high=np.concatenate([s.high for s in space_list]),
    385             dtype=np.result_type(*[s.dtype for s in space_list]),

/usr/local/lib/python3.10/dist-packages/numpy/core/overrides.py in concatenate(*args, **kwargs)

ValueError: need at least one array to concatenate

**Comment by ahalev** [comment]
This should be fixed in recent updates. Can you try upgrading with `pip install -U python-microgrid`? If not doesn't work, try cloning and installing from source.
