### ISSUE TITLE
Simulating Prosumers within a microgrid as part of a aggregate market model

### ISSUE THREAD

**Issue by AndelBenjamin** [ahalev/python-microgrid#98]
Hi all, I'm super happy to have found this great project!
Sadly, I think I might not be able to utelise it for my usecase, so I hope you might be able to tell whether I should look into altering the library to my usecase or find another.

I want to simulate a microgrid of prosumers with the aim to feed its state into a market model for its aggregated prosumers to trade power between them. Thus, I want the cadastres (house holds) to be it's own entity who does not freely share power within its microgrid.
Power would only be shared within the microgrid if the cadastre choose to export power rather than store / use it.

This project seems to not meet this requirement, however it seems like it should be possible to alter it.
As a hack one could make each cadastre a separate microgrid with 2 grid modules, 1 to monitor the energy being shared through the microgrid trading and the other to monitor imported energy from the utility grid.

What are your thoughts?? Is it a good idea to try and bend the library to my will or should I pursue other avenues? Any feedback is welcome :)

**Comment by ahalev** [comment]
I think this is doable, perhaps by treating each household as a separate microgrid and having one module handle the pool of traded energy. 

You may need to define a new subclass of `BaseModule` to do this, although I think you could easily adapt `BatteryModule` to fit your use case. 

That doesn't sound like a hack to me, it sounds like a reasonable application of the simulator's capabilities :).
